(function(){function I(e,r,a){var b=document.createElement("canvas"),f=b.getContext("2d");b.width=e;b.height=r;f.fillRect(0,0,e,r);f.fillStyle="white";f.beginPath();f.moveTo(a[0],a[1]);for(e=1;16>=e;e++)f.lineTo(a[2*e],a[2*e+1]);for(e=73;68<=e;e--)f.lineTo(a[2*e],a[2*e+1]);f.lineTo(a[0],a[1]);f.fill();f.fillStyle="black";f.beginPath();r=.8*(a[67]-a[61]);f.moveTo(a[62],a[63]-r);for(e=32;35>=e;e++)f.lineTo(a[2*e],a[2*e+1]-r);var c=.3*(a[24]-a[108]);f.lineTo(a[108]+c,a[109]);c=.3*(a[17]-a[115]);for(e=
55;59>=e;e++)f.lineTo(a[2*e],a[2*e+1]+c);c=.3*(a[96]-a[8]);f.lineTo(a[96]-c,a[97]);f.lineTo(a[62],a[63]-r);r=.5*(a[39]-a[137]);f.moveTo(a[34],a[35]-r);for(e=18;21>=e;e++)f.lineTo(a[2*e],a[2*e+1]-r);f.lineTo(a[78],a[79]);c=.4*(a[61]-a[81]);for(e=40;41>=e;e++)f.lineTo(a[2*e],a[2*e+1]+c);f.lineTo(a[0],a[1]);f.lineTo(a[34],a[35]-r);r=.5*(a[49]-a[147]);f.moveTo(a[44],a[45]-r);for(e=23;26>=e;e++)f.lineTo(a[2*e],a[2*e+1]-r);f.lineTo(a[32],a[33]);c=.4*(a[61]-a[93]);for(e=46;47>=e;e++)f.lineTo(a[2*e],a[2*
e+1]+c);f.lineTo(a[84],a[85]);f.lineTo(a[44],a[45]-r);f.fill();return b}function D(e,r,a,b,f,c){for(var p=a-b+1,l=e-b+1,g=parseInt(.5*b),m,n=1/b,d=r;d<a;d++)for(var h=d*e,k=0;k<l;k++)if(m=0,f[4*(h+k)]!=f[4*(h+(k+g))]||f[4*(h+(k+g))]!=f[4*(h+(k+b-1))]){for(var q=k+b-1;q>=k;q--)m+=f[4*(h+q)];m*=n;c[4*(h+(k+g))]=m}for(k=0;k<e;k++)for(h=4*k,a=4*e,d=r;d<p;d++)if(m=0,c[d*a+h]==c[(d+g)*a+h]&&c[(d+g)*a+h]==c[(d+b-1)*a+h])f[(d+g)*a+h]=c[d*a+h];else{for(l=d+b-1;l>=d;l--)m+=c[l*a+h];m*=n;f[(d+g)*a+h]=m}}function J(e,
r,a,b){for(var f=parseInt(.5*b),c,p=1/b,l=a.slice(),g=e-b+1,m=0;m<r;m++)for(var n=m*e,d=0;d<g;d++){c=0;for(var h=d+b-1;h>=d;h--)c+=a[4*(n+h)+1];c*=p;l[4*(n+(d+f))+1]=c}r=r-b+1;for(d=0;d<e;d++)for(n=4*d,g=4*e,m=0;m<r;m++){c=0;for(h=m+b-1;h>=m;h--)c+=l[h*g+n+1];c*=p;a[(m+f)*g+n+1]=c}}function K(e,r,a,b){for(var f=parseInt(.5*b),c=1/b,p,l,g,m=a.slice(),n=e-b+1,d=0;d<r;d++)for(var h=d*e,k=0;k<n;k++){g=l=p=0;for(var q=k+b-1;q>=k;q--)p+=a[4*(h+q)],l+=a[4*(h+q)+1],g+=a[4*(h+q)+2];p*=c;l*=c;g*=c;m[4*(h+(k+
f))]=p;m[4*(h+(k+f))+1]=l;m[4*(h+(k+f))+2]=g}r=r-b+1;for(k=0;k<e;k++)for(h=4*k,n=4*e,d=0;d<r;d++){g=l=p=0;for(q=d+b-1;q>=d;q--)p+=m[q*n+h],l+=m[q*n+h+1],g+=m[q*n+h+2];p*=c;l*=c;g*=c;a[(d+f)*n+h]=p;a[(d+f)*n+h+1]=l;a[(d+f)*n+h+2]=g}}var u=btbpExample.features;u.kernalFace;u.kernalComplexion;u.kernalForehead;u.kernalEyebrow;u.kernalLip;var E,H=0,F=0,G=0,A=btbpExample.settings;u.applyFoundation=function(e,r,a,b,f){var c=e.width,p=e.height,l=document.createElement("canvas"),g=l.getContext("2d");l.width=
c;l.height=p;g.fillRect(0,0,c,p);g.fillStyle="white";g.beginPath();g.moveTo(b[0],b[1]);for(c=1;16>=c;c++)g.lineTo(b[2*c],b[2*c+1]);for(c=73;68<=c;c--)g.lineTo(b[2*c],b[2*c+1]);g.lineTo(b[0],b[1]);g.fill();g.fillStyle="black";g.beginPath();g.moveTo(b[96],b[97]);for(c=49;59>=c;c++)g.lineTo(b[2*c],b[2*c+1]);g.lineTo(b[96],b[97]);g.moveTo(b[34],b[35]);for(c=18;21>=c;c++)g.lineTo(b[2*c],b[2*c+1]);p=.5*(b[75]+b[77]);for(c=21;17<=c;c--)g.lineTo(b[2*c],b[2*c+1]+.33*(p-b[2*c+1]));g.lineTo(b[34],b[35]);g.moveTo(b[72],
b[73]);for(c=37;41>=c;c++)g.lineTo(b[2*c],b[2*c+1]);g.lineTo(b[72],b[73]);g.moveTo(b[44],b[45]);for(c=23;26>=c;c++)g.lineTo(b[2*c],b[2*c+1]);p=.5*(b[87]+b[89]);for(c=26;22<=c;c--)g.lineTo(b[2*c],b[2*c+1]+.33*(p-b[2*c+1]));g.lineTo(b[44],b[45]);g.moveTo(b[84],b[85]);for(c=43;47>=c;c++)g.lineTo(b[2*c],b[2*c+1]);g.lineTo(b[84],b[85]);g.fill();H=b[67];F=.5*(b[137]+b[147]);G=.5*(b[35]+b[53]);var m=l.getContext("2d"),c=e.getContext("2d");r=r.getContext("2d");var l=a.x,g=a.y,c=c.getImageData(l,g,a.width,
a.height),p=c.data,m=m.getImageData(l,g,a.width,a.height).data,n=c.width,d=c.height;F-=g;G-=g;var h=m.slice(),k=parseInt(G),q;D(n,k,d,u.kernalFace,m,h);k=parseInt(F);q=parseInt(G+u.kernalEyebrow-1);D(n,k,q,u.kernalEyebrow,m,h);k=0;q=parseInt(F+u.kernalForehead-1);D(n,k,q,u.kernalForehead,m,h);var h=p.slice(),v;f&&(e=v=I(e.width,e.height,b).getContext("2d").getImageData(l,g,a.width,a.height).data,a=e.slice(),D(n,0,d,u.kernalFace,e,a),K(n,d,h,u.kernalComplexion));if(A.MatchFoundation){H-=g;b=parseInt(H*
n*4);e=A.foudataionShades;n=h.length;d=0;k=[];for(a=0;256>a;a++)k[a]=0;for(a=0;a<n;a+=4)a<b&&255==m[a]&&(k[h[a]]++,d++);q=.2*d;var s=.15*d,d=0,t,x;for(a=0;256>a;a++)if(d+=k[a],k[a]=0,d>q){t=a;break}d=0;for(a=255;0<=a;a--)if(d+=k[a],k[a]=0,d>s){x=a;break}var B=s=q=k=d=0;for(a=0;a<n;a+=4)B=h[a],a<b&&255==m[a]&&B>t&&B<x&&(k+=B,q+=h[a+1],s+=h[a+2],d++);0<d&&(k/=d,q/=d,s/=d);t=Math.abs(k-e[0][0])+Math.abs(q-e[0][1])+Math.abs(s-e[0][2]);x=0;for(a=1;a<e.length;a++)b=Math.abs(k-e[a][0])+Math.abs(q-e[a][1])+
Math.abs(s-e[a][2]),b<t&&(t=b,x=a);A.setFoundationShade(x);A.MatchFoundation=!1}x=A.FoundationShade;t=x[1]/x[0];x=x[2]/x[0];for(var B=p.length,C=A.FoundationIntensity,w=3*A.ComplexionIntensity,z=1/255,y=0;y<B;y+=4)q=m[y]*C,0<q&&(e=p[y],a=p[y+1],b=p[y+2],f&&(s=v[y],0<s&&(n=w*(h[y]-e),0>n&&(n=0),d=w*(h[y+1]-a),0>d&&(d=0),k=w*(h[y+2]-b),0>k&&(k=0),n+=e,d+=a,k+=b,255<n&&(n=255),255<d&&(d=255),255<k&&(k=255),e=e*z*(255-s)+n*z*s,a=a*z*(255-s)+d*z*s,b=b*z*(255-s)+k*z*s)),p[y]=e*z*(255-q)+1*e*z*q,p[y+1]=
a*z*(255-q)+e*t*z*q,p[y+2]=b*z*(255-q)+e*x*z*q);r.putImageData(c,l,g)};u.applyComplexion=function(e,r,a,b){var f=I(e.width,e.height,b).getContext("2d"),c=e.getContext("2d");r=r.getContext("2d");e=a.x;b=a.y;var c=c.getImageData(e,b,a.width,a.height),p=c.data;a=f.getImageData(e,b,a.width,a.height).data;var l=c.width,g=c.height,f=a.slice();D(l,0,g,u.kernalFace,a,f);f=p.slice();K(l,g,f,u.kernalComplexion);for(var m,n,d,h,k,q=p.length,v=3*A.ComplexionIntensity,s=1/255,t=0;t<q;t+=4)k=a[t],0<k&&(l=p[t],
g=p[t+1],m=p[t+2],n=v*(f[t]-l),0>n&&(n=0),d=v*(f[t+1]-g),0>d&&(d=0),h=v*(f[t+2]-m),0>h&&(h=0),n+=l,d+=g,h+=m,255<n&&(n=255),255<d&&(d=255),255<h&&(h=255),p[t]=l*s*(255-k)+n*s*k,p[t+1]=g*s*(255-k)+d*s*k,p[t+2]=m*s*(255-k)+h*s*k);r.putImageData(c,e,b)};u.applyLipstick=function(e,r,a,b){var f=e.width,c=e.height,p=document.createElement("canvas"),l=p.getContext("2d");E=document.createElement("canvas");var g=E.getContext("2d");p.width=f;p.height=c;E.width=f;E.height=c;l.fillRect(0,0,f,c);g.fillRect(0,
0,f,c);l.fillStyle="white";l.beginPath();l.moveTo(b[96],b[97]);for(f=49;59>=f;f++)l.lineTo(b[2*f],b[2*f+1]);l.lineTo(b[96],b[97]);l.fill();l.fillStyle="black";l.beginPath();l.moveTo(b[120],b[121]);for(f=61;67>=f;f++)l.lineTo(b[2*f],b[2*f+1]);l.lineTo(b[120],b[121]);l.fill();g.fillStyle="white";g.beginPath();g.moveTo(b[96],b[97]);g.lineTo(b[120],b[121]);for(f=67;64<=f;f--)g.lineTo(b[2*f],b[2*f+1]);g.lineTo(b[108],b[109]);for(f=55;59>=f;f++)g.lineTo(b[2*f],.5*(b[2*f+1]+b[133]));g.lineTo(b[96],b[97]);
g.fill();g=p.getContext("2d");f=E.getContext("2d");p=e.getContext("2d");r=r.getContext("2d");e=a.x;b=a.y;p=p.getImageData(e,b,a.width,a.height);l=p.data;g=g.getImageData(e,b,a.width,a.height).data;a=f.getImageData(e,b,a.width,a.height).data;var m=p.width,n=p.height,d,h;d=A.LipColor;0==d[0]&&0==d[1]&&0==d[2]?h=f=c=d=0:d[0]>=d[1]&&d[0]>=d[2]?(f=1,c=d[1]/d[0],d=d[2]/d[0],h=0):d[1]>=d[2]?(f=d[0]/d[1],c=1,d=d[2]/d[1],h=1):(f=d[0]/d[2],c=d[1]/d[2],d=1,h=2);J(m,n,g,u.kernalLip);var k=l.slice();J(m,n,k,u.kernalFace);
for(var q,v,s,t=l.length,x=A.LipIntensity,B=4*A.LipGlossValue/(255*x),C=1/255,w=0;w<t;w+=4)s=g[w+1]*x,0<s&&(m=l[w],n=l[w+1],q=l[w+2],v=l[w+h],m=m*C*(255-s)+v*f*C*s,n=n*C*(255-s)+v*c*C*s,q=q*C*(255-s)+v*d*C*s,0<a[w]&&(v=l[w+1]-k[w+1],0>v&&(v=0),v*=s*B,m+=v,n+=v,q+=v,255<m&&(m=255),255<n&&(n=255),255<q&&(q=255)),l[w]=m,l[w+1]=n,l[w+2]=q);r.putImageData(p,e,b)}})();
