var btbpExample={appId:"TestAppForDemo",loader:{queuePreloader:null},imageData:{webcam:{stream:null},picture:{}},dom:{},gui:{},drawing:{},features:{},drawing3d:{t3d:{}},stats:{}};
(function(){function b(){$("#"+a.content).html(mirrorContent);btbpExample.mirrorOptions=a;btbpExample.appConfig=a.mirror_config;btbpExample.start();onStartClicked()}var a=this.options;this.BTBPMirror=function(a){var b={content:"",key:"",mirror_config:{BeautyFeatureList:[],SkinFeatureList:[],DeepTagList:[],auto_reset:!1,show_settings:!1,beautyFace:!0,auto_reset_time_interval:18E4}};if(a&&"object"===typeof a)for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);this.options=b};BTBPMirror.prototype.startMirror=
function(){a=this.options;void 0==a.key||0==a.key.length?alert("Key is mandatory"):$.ajax({type:"GET",url:"https://api.btbp.org/deeptag/Appservice.svc/licensestatus/"+a.key,success:function(a){a.Status?b():console.log("IFace Authentication failed, "+a.Message)},error:function(){console.log("IFace Authentication service call failed!");b()}})};BTBPMirror.prototype.stopMirror=function(){btbpExample.imageData.webcam.stopStream();$("#"+a.content).html("")};BTBPMirror.prototype.stopCamera=function(){btbpExample.imageData.webcam.stopStream()};
BTBPMirror.prototype.startCamera=function(){btbpExample.imageData.webcam.startStream()}})();var hostUrl="BTBP/",btbpv4BaseURL=hostUrl+"js/libs/btbp_wasm/",support="object"===typeof WebAssembly;support||(btbpv4BaseURL=hostUrl+"js/libs/btbp_asmjs/");var btbpv4={locateFile:function(b){return btbpv4BaseURL+b}};
btbpExample.start=function(){btbpExample.loader.preload([hostUrl+"js/upload.js",hostUrl+"js/common.js",hostUrl+"js/vendor/dat.gui.min.js",btbpv4BaseURL+"BRFv4_JS_BT011117_v4.0.1_commercial.js",hostUrl+"js/libs/highlight/highlight.pack.js",hostUrl+"js/libs/createjs/easeljs-0.8.2.min.js",hostUrl+"js/utils/BTBPDOMUtils.js",hostUrl+"js/utils/BTBPSetupSettings.js",hostUrl+"js/utils/BTBPDrawingUtils_CreateJS.js",hostUrl+"js/utils/BTBPSetupWebcam.js",hostUrl+"js/utils/BTBPSetupExample.js",hostUrl+"js/utils/BTBPPointUtils.js",
hostUrl+"js/utils/BTBPExtendedFace.js",hostUrl+"js/face_libs/BTBPFeatures.js",hostUrl+"js/face_libs/btbp_engine.js"],function(){btbpExample.init("webcam")})};btbpExample.trace=function(b,a){};
(function(){var b=btbpExample.loader;b.preload=function(a,e){function c(a){b.setProgressBar(a.loaded,!0)}function d(a){b.setProgressBar(1,!1);e&&e()}if(null===b.queuePreloader&&a){var f=b.queuePreloader=new createjs.LoadQueue(!0);f.on("progress",c);f.on("complete",d);f.loadManifest(a,!0)}};b.loadExample=function(a,e){var c=b.queueExamples=new createjs.LoadQueue(!0);c.on("progress",function(a){b.setProgressBar(a.loaded,!0)});c.on("complete",function(a){b.setProgressBar(1,!1);e&&e()});c.loadManifest(a,
!0)};b.setProgressBar=function(a,b){var c=document.getElementById("_progressBar");if(c){0>a&&(a=0);1<a&&(a=1);var d=Math.round(640*a);c.style.width=d+"px";c.style.backgroundColor="#"+"#ccc".toString(16);c.style.display=b?"block":"none"}}})();var loaderInterval;
function onStartClicked(){btbpExample.config.isStarted=!0;$("#loader_deeptag_container").hide();$("#deeptag_status_txt").text("Please place your face with in the red box");clearInterval(loaderInterval);btbpExample.config.isReady?($(".ac").css({display:"block"}),$("#launch_screen").fadeOut(),getLocation()):($("#loader_launch_screen").show(),loaderInterval=setInterval(function(){onStartClicked()},1E3))}
function onRetryClicked(){$("#loader_launch_screen").show();$("#error_container").hide();btbpExample.init("webcam")}function onRestartClicked(){onReanalyze();btbpExample.settings.reset();clearClimateDetails();btbpExample.config.isFoundationClicked=!1}function onLipstickShades(){$("#foundationshades_container").fadeOut();$("#lipsShades_container").fadeIn();$("#lbl_lipShades").css({color:"#6eb6ff"});$("#lbl_foundationShades").css({color:"white"})}
function onFoundationShades(){btbpExample.config.isFoundationClicked||(btbpExample.settings.isFoundationClicked=!0,btbpExample.settings.Foundation=!0);$("#lipsShades_container").fadeOut();$("#foundationshades_container").fadeIn();$("#lbl_lipShades").css({color:"white"});$("#lbl_foundationShades").css({color:"#6eb6ff"})}function onSettingsClicked(){btbpExample.callbacks.toggleDataGUI()}(function(){btbpExample.config={isStarted:!1,isReady:!1,isFoundationClicked:!1,isAutoRest:!0,resetTimeout:60}})();
$(window).resize(function(){try{var b=document.getElementById("app_container").clientWidth;document.getElementById("_foundationshades").style.width=.8*b+"px"}catch(a){console.log("Exception : "+a)}try{setupAppLayout()}catch(e){}});
var mirrorContent="",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'<div class="app_container align_center_horizontal" id="app_container">',mirrorContent=mirrorContent+'\t\t<div class="screens">',mirrorContent=mirrorContent+'\t\t\t<div id="launch_screen" style="display:block;">',mirrorContent=mirrorContent+'\t\t\t\t<div class="content">',mirrorContent=mirrorContent+"\t\t\t\t\t",mirrorContent=mirrorContent+"\t\t\t\t\t<br/>",mirrorContent=mirrorContent+"\t\t\t\t\t",mirrorContent=mirrorContent+
"\t\t\t\t\t<br/>",mirrorContent=mirrorContent+"\t\t\t\t\t<br/>",mirrorContent=mirrorContent+"\t\t\t\t\t<br/>",mirrorContent=mirrorContent+"\t\t\t\t\t<br/>",mirrorContent=mirrorContent+'\t\t\t\t\t<div id="error_container" style="display:none;">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<span id="error_message"></span>',mirrorContent=mirrorContent+"\t\t\t\t\t\t<br/>",mirrorContent=mirrorContent+"\t\t\t\t\t\t<br/>",mirrorContent=mirrorContent+'\t\t\t\t\t\t<a class="btn" href="javascript:onRetryClicked();">RETRY</a>',
mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t",mirrorContent=mirrorContent+'\t\t\t\t<div id="loader_launch_screen" style="display:none;">',mirrorContent=mirrorContent+'\t\t\t\t\t<div class="loader_container align_center">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<img src="BTBP/img/Spinner.gif" width="80" height="80" />',mirrorContent=mirrorContent+"\t\t\t\t\t\t<br/>",mirrorContent=mirrorContent+
"\t\t\t\t\t\t<span>Loading</span>",mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t<div id="ui_controlls" class="ui_controlls" style="display:none;">',mirrorContent=mirrorContent+"\t\t\t\t",mirrorContent=mirrorContent+'\t\t\t\t<div id="controls_menu">',mirrorContent=
mirrorContent+'\t\t\t\t\t<div style="position: relative;width:100%;height:100%;">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="controls_selection">',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t\t<div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t\t<a href="javascript:onLipstickShades()" id="lbl_lipShades" style="color:#6eb6ff;">Lipstick</a>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t\t<div>",mirrorContent=
mirrorContent+'\t\t\t\t\t\t\t\t\t\t<a href="javascript:onFoundationShades()"  id="lbl_foundationShades">Foundation</a>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t<div class="controls_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div id="lipsShades_container" class="color_shades" style="display:table;width:100%;height:100%;">',mirrorContent=mirrorContent+
'\t\t\t\t\t\t\t\t<ul id="_lipshades" class="center_vertical">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</ul>",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div id="foundationshades_container" class="color_shades" style="display:none;">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div style="display:table;width:100%;height:100%;">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<div style="display:table-cell;vertical-align:middle;">',
mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<ul id="_foundationshades">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</ul>",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+
"",mirrorContent=mirrorContent+'\t\t\t\t<div class="results_left_panel_container">',mirrorContent=mirrorContent+'\t\t\t\t\t<div class="">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<div class="concerns_list" id="concerns_list">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<div class="results_bottom_panel_container">',
mirrorContent=mirrorContent+"\t\t\t\t\t",mirrorContent=mirrorContent+'\t\t\t\t\t<div id="loader_deeptag_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<img id="deeptag_status_loader" src="BTBP/img/Spinner_black.gif" width="40" height="40" />',mirrorContent=mirrorContent+'\t\t\t\t\t\t<span id="deeptag_status_txt">Analzing...</span>',mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t<div class="image_rejection_cotainer">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<span id="deeptag_rejection_txt">Please align your face within the red box</span>',
mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t",mirrorContent=mirrorContent+'\t\t\t\t\t<div id="tag_item_list_parent">',mirrorContent=mirrorContent+'\t\t\t\t\t\t<div class="tag_item_list">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="gender_item">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value" id="txt_gender"></div>',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container">',
mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img id="Male_Female_img" src="BTBP/img/Gender_Disabled_Icon.png" />',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">Gender</div>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="age_item">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value"></div>',mirrorContent=
mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img src="BTBP/img/Age_Icon.png" />',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<span id="age_index" class="align_center"></span>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">Age</div>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="skin_type_item">',
mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value"></div>',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container" style="height:50%;">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img id="skin_type_img" class="align_center"  src="BTBP/img/skintype/SkinType_GreyShade.png" style="height:100%;" />',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img id="skin_type_selected_img" class="align_center" src="BTBP/img/skintype/SkinType_PantoneShade.png" style="height:100%;display:none;" />',
mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<span id="skin_type_index" class="align_center"></span>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">Skin Type</div>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div> ",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="pollution_item">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value" id="txt_pollution_value"></div>',
mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img src="BTBP/img/Air_Quality Icon.png" />',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<span id="pollution_index" class="align_center"></span>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">Air Quality</div>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=
mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="location_item">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value" id="txt_location_value"></div>',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img src="BTBP/img/Location_Icon.png" />',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">Location</div>',mirrorContent=mirrorContent+
"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t<div class="tag_item" id="uv_item">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_value" id="txt_uv_value">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_image_container">',mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t\t<img src="BTBP/img/UV_index_icon.png" />',mirrorContent=mirrorContent+
'\t\t\t\t\t\t\t\t\t<span id="uv_index" class="align_center"></span>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t\t\t\t\t<div class="tag_name">UV Index</div>',mirrorContent=mirrorContent+"\t\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<div id="data-gui-container">',mirrorContent=
mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t\t\t",mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"\t\t\t\t",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<img id="restart_btn" src="BTBP/img/Reset icon.png" width="40" style="position:absolute;left:10px;bottom:13%;cursor:pointer;z-index:100;" onclick="onRestartClicked()"/>',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<img id="settings_btn" src="BTBP/img/Settings Icon.png" width="40" style="position:absolute;right:10px;bottom:13%;cursor:pointer;z-index:100;" onclick="onSettingsClicked()"/>',
mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t<div id="_wrapper">',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<div id="_content">',mirrorContent=mirrorContent+'\t\t\t\t\t<video id="_webcam" autoplay muted playsInline></video>',mirrorContent=mirrorContent+'\t\t\t\t\t<canvas id="_imageData"></canvas>',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+
'\t\t\t\t\t<canvas id="_faceSub"></canvas>',mirrorContent=mirrorContent+'\t\t\t\t\t<canvas id="_mask"></canvas>',mirrorContent=mirrorContent+'\t\t\t\t\t<canvas id="_t3d"></canvas>',mirrorContent=mirrorContent+'\t\t\t\t\t<canvas id="_f3d"></canvas>',mirrorContent=mirrorContent+'\t\t\t\t\t<canvas id="_drawing"></canvas>',mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t\t<div id="_stats"></div>',mirrorContent=mirrorContent+
'\t\t\t\t\t<div id="_progressBar"></div>',mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+"",mirrorContent=mirrorContent+'\t\t\t\t<div id="_subline"></div>',mirrorContent=mirrorContent+'\t\t\t\t<div id="_highlight" style="display:none">',mirrorContent=mirrorContent+'\t\t\t\t\t<pre><code class="javascript" id="_gist"></code></pre>',mirrorContent=mirrorContent+"\t\t\t\t</div>",mirrorContent=mirrorContent+'\t\t\t\t<a id="_saveImage" download="Original_Image"></a>',
mirrorContent=mirrorContent+"\t\t\t</div>",mirrorContent=mirrorContent+"\t\t</div>",mirrorContent=mirrorContent+"\t</div>";
