var Latitude=0,Longitude=0,Deep_Tag_key=btbpExample.mirrorOptions.key,Client="BTBP",LicensedDeepTags=[],LicensedFeatureTags=[],MSMDeepTags="GENDER AGEGROUP DiscreteAge SKINTYPE GEOLOCATION_CITY UVINDEX POLLUTION_AQI".split(" "),MSMSkinTags="WRINKLES_SEVERITY_SCORE ACNE_SEVERITY_SCORE REDNESS_SEVERITY_SCORE PORES_SEVERITY_SCORE SPOTS_SEVERITY_SCORE UNEVEN_SKINTONE_SEVERITY_SCORE DARK_CIRCLES_SEVERITY_SCORE DEHYDRATION_SEVERITY_SCORE LIP_ROUGHNESS_SEVERITY_SCORE OILINESS_SEVERITY_SCORE".split(" "),
DeepTags={GENDER:"GENDER",AGEGROUP:"AGEGROUP",DiscreteAge:"DiscreteAge",SKINTYPE:"SKINTYPE",GEOLOCATION_CITY:"GEOLOCATION_CITY",UVINDEX:"UVINDEX",POLLUTION_AQI:"POLLUTION_AQI",WRINKLES_SEVERITY_SCORE:"WRINKLES_SEVERITY_SCORE",ACNE_SEVERITY_SCORE:"ACNE_SEVERITY_SCORE",PORES_SEVERITY_SCORE:"PORES_SEVERITY_SCORE",SPOTS_SEVERITY_SCORE:"SPOTS_SEVERITY_SCORE",REDNESS_SEVERITY_SCORE:"REDNESS_SEVERITY_SCORE",UNEVEN_SKINTONE_SEVERITY_SCORE:"UNEVEN_SKINTONE_SEVERITY_SCORE",DARK_CIRCLES_SEVERITY_SCORE:"DARK_CIRCLES_SEVERITY_SCORE",
LIP_ROUGHNESS_SEVERITY_SCORE:"LIP_ROUGHNESS_SEVERITY_SCORE",DEHYDRATION_SEVERITY_SCORE:"DEHYDRATION_SEVERITY_SCORE",OILINESS_SEVERITY_SCORE:"OILINESS_SEVERITY_SCORE"},uploadStopTimeout,ANALYZE_IMAGE_REQUEST_CODE;
function startAnalysis(a){0<LicensedDeepTags.length+LicensedFeatureTags.length&&(console.log("Analysis started"),$("#loader_deeptag_container").show(),$("#deeptag_rejection_txt").hide(),$("#deeptag_status_txt").text("Analyzing..."),imageBase64String=onGetBase64FromCanvas(a),onImgUpload(imageBase64String))}function onGetBase64FromCanvas(a){return a.toDataURL("image/jpeg",1)}
function getLicensedDeepTags(){var a=getServiceURL()+"authorizedtags/"+Deep_Tag_key;HttpClient.Get(a,function(a){onGetLicensedTagsSuccess(a)},function(){console.log("getLicensedDeepTags service call failed");hideProgress();customAlert.show("Please check your internet connection and try again.",function(){showProgress();getLicensedDeepTags()},"Try Again")})}
function onGetLicensedTagsSuccess(a){a=JSON.parse(a);LicensedTags=[];for(var b=0;b<a.length;b++)LicensedTags.push(a[b].TagName);try{if(0==LicensedTags.length){hideProgress();customAlert.show("No Tags found.",function(){showProgress();getLicensedDeepTags()},"Try Again");return}}catch(c){}onImgUpload(imageBase64String)}
function getTags(){for(var a=[],b=0;b<MSMDeepTags.length;b++){var c=MSMDeepTags[b];-1<LicensedDeepTags.indexOf(c)&&a.push(c)}for(b=0;b<MSMSkinTags.length;b++)c=MSMSkinTags[b],-1<LicensedFeatureTags.indexOf(c)&&a.push(c);return a}var UPLOAD_TIME_LIMIT=18E4;
function onImgUpload(a){var b=ANALYZE_IMAGE_REQUEST_CODE=(new Date).getTime();clearTimeout(uploadStopTimeout);uploadStopTimeout=setTimeout(function(){var a=((new Date).getTime()-c)/1E3;console.log("Upload Time Out (in seconds) : "+a);console.log("uploadStopTimeout happend...");onUploadFailed("Please check your internet connection")},UPLOAD_TIME_LIMIT);var c=(new Date).getTime(),f=sessionStorage.Email,f=(new Date).getTime()+"@btbp.org",e=getTags();-1!=a.indexOf(",")&&(a=a.split(",")[1]);a=a.match(/.{1,1024}/g);
jsonText=JSON.stringify({APIKey:Deep_Tag_key,UserId:f,ClientId:Client,Latitude:Latitude,Longitude:Longitude,Tags:e,ImageBytes:a});var f=getServiceURL()+"GetTags",g=createCORSRequest("POST",f);g.onload=function(){if(4==g.readyState&&200==g.status){clearTimeout(uploadStopTimeout);var a=JSON.parse(g.responseText);(new Date).getTime();onDeepTagSuccess(a,b)}else 401==g.status?(clearTimeout(uploadStopTimeout),a=JSON.parse(g.responseText),console.log("Unauthorized service call"),a=JSON.stringify(a)):(clearTimeout(uploadStopTimeout),
a=JSON.parse(g.responseText),a=JSON.stringify(a),console.log("Operation failed response")),onImageRejected(a)};g.onerror=function(){onUploadFailed("Please check your internet connection")};g.setRequestHeader("Content-Type","application/json");g.send(jsonText)}function skinConcern(){this.Image=this.Name="";this.Severity=0}function DeepTagInfo(){this.UVIndex=this.Location=this.Pollution=this.skinType=this.Age=this.Gender=""}
function onDeepTagSuccess(a,b){if(b!=ANALYZE_IMAGE_REQUEST_CODE)console.log("analysis results skipped");else{var c=a.Tags,f=c.length;new skinConcern;new skinConcern;new skinConcern;new skinConcern;new skinConcern;new skinConcern;new skinConcern;new skinConcern;for(var e=new DeepTagInfo,g=[],m=0;m<f;m++){var d=c[m];if(-1!=MSMDeepTags.indexOf(d.TagName))switch(d.TagName){case DeepTags.GENDER:d.Status?(d=d.TagValues[0].Value.toUpperCase(),e.Gender=d):e.Gender="NA";break;case DeepTags.AGEGROUP:e.Age=
d.Status?d.TagValues[0].Value:"NA";break;case DeepTags.SKINTYPE:e.skinType=d.Status?d.TagValues[0].Value:"NA";break;case DeepTags.GEOLOCATION_CITY:e.Location=d.Status?d.TagValues[0].Value:"NA";break;case DeepTags.UVINDEX:e.UVIndex=d.Status?d.TagValues[0].Value:"NA";break;case DeepTags.POLLUTION_AQI:e.Pollution=d.Status?d.TagValues[0].Value:"NA"}else if(-1!=MSMSkinTags.indexOf(d.TagName))if(d.Status){var k=new skinConcern;k.Name=getFeatureNameByTagName(d.TagName);k.Severity=d.TagValues[0].Value;0!=
k.Name.length&&g.push(k)}else{onImageRejected(d.Message);return}}$("#loader_deeptag_container").hide();setupResults(g);showDeepTagInfo(e)}}
function getFeatureNameByTagName(a){var b="";switch(a){case DeepTags.GENDER:b="Gender";break;case DeepTags.AGEGROUP:b="Gender";break;case DeepTags.SKINTYPE:b="Gender";break;case DeepTags.GEOLOCATION_CITY:b="Gender";break;case DeepTags.UVINDEX:b="Gender";break;case DeepTags.POLLUTION_AQI:b="Gender";break;case DeepTags.WRINKLES_SEVERITY_SCORE:b="Wrinkles";break;case DeepTags.ACNE_SEVERITY_SCORE:b="Acne";break;case DeepTags.PORES_SEVERITY_SCORE:b="Pores";break;case DeepTags.SPOTS_SEVERITY_SCORE:b="Spots";
break;case DeepTags.REDNESS_SEVERITY_SCORE:b="Redness";break;case DeepTags.UNEVEN_SKINTONE_SEVERITY_SCORE:b="Uneven Skintone";break;case DeepTags.DARK_CIRCLES_SEVERITY_SCORE:b="Dark Circles";break;case DeepTags.LIP_ROUGHNESS_SEVERITY_SCORE:b="Lip Health";break;case DeepTags.OILINESS_SEVERITY_SCORE:b="Oiliness";break;case DeepTags.DEHYDRATION_SEVERITY_SCORE:b="Dehydration"}return b}
function showDeepTagInfo(a){try{var b=0,c=a.Gender;0!=c.length?(-1!=c.indexOf("NA")?$("#Male_Female_img").attr("src","BTBP/img/Gender_Disabled_Icon.png"):(c="MALE"==c?"Male":"Female",$("#Male_Female_img").attr("src","BTBP/img/"+c+".png"),$("#txt_gender").html(c)),$("#Male_Female_img").show(),b++):$("#gender_item").hide();if(0!=a.skinType.length){var f=a.skinType;-1!=f.indexOf("NA")?$("#skin_type_selected_img").hide():(c="SkinType_"+f,$("#skin_type_selected_img").show(),$("#skin_type_selected_img").attr("src",
"BTBP/img/skintype/"+c+".png"));$("#skin_type_index").html(f);b++}else $("#skin_type_item").hide();0!=a.Age.length?($("#age_index").html(a.Age),b++):$("#age_item").hide();0!=a.Pollution.length?($("#pollution_index").html(a.Pollution),b++):$("#pollution_item").hide();0!=a.Location.length?($("#txt_location_value").html(a.Location),b++):$("#location_item").hide();0!=a.UVIndex.length?($("#uv_index").html(a.UVIndex),b++):$("#uv_item").hide();0==b?$(".results_bottom_panel_container").hide():$(".results_bottom_panel_container").show()}catch(e){console.log("Exception at showDeepTagInfo :"+
e)}}function onImageRejected(a){console.log(a);$("#loader_deeptag_container").hide();$("#deeptag_rejection_txt").show();$("#deeptag_rejection_txt").text(a);setTimeout(function(){onReanalyze()},6E3)}function onReanalyze(){btbpExample.settings.isAnalysisStated=!1;$("#loader_deeptag_container").hide();$("#deeptag_rejection_txt").show();$("#deeptag_rejection_txt").text("Please align your face within the red box")}
function createCORSRequest(a,b){var c=new XMLHttpRequest;"withCredentials"in c?c.open(a,b,!0):"undefined"!=typeof XDomainRequest?(c=new XDomainRequest,c.open(a,b)):c=null;return c}function onUploadFailed(a){clearTimeout(uploadStopTimeout);onImgUpload(imageBase64String)}var prevSelectedSkinConern=0,concernList=[];
function setupFeatureResults(a){prevSelectedSkinConern=0;concernList=a;try{if(null==a&&0!=a.length)console.log("featureList mull "),$(".results_left_panel_container").hide();else{$(".results_left_panel_container").show();var b=a.length,c=90,c=isMobile()?100:90,f=getElement("concerns_list");f.innerHTML="";getElement("app_container");for(var e=0;e<b;e++){var g=a[e],m=g.Severity,d=document.createElement("div");d.index=e;d.style.width=c+"px";var k=document.createElement("div");k.setAttribute("class",
"concern_severity");var l=parseInt(.7*c);k.style.height=l+"px";if(-1!=m.indexOf("0")){var h=document.createElement("canvas");h.width=l;h.height=l;drawCircle(h,4)}else h=document.createElement("canvas"),h.width=l,h.height=l,drawCircle(h,4),drawSeverity(h,m,4,16);k.appendChild(h);var n=document.createElement("div");n.setAttribute("class","txt_concern");n.innerHTML=g.Name;d.appendChild(k);d.appendChild(n);f.appendChild(d)}}}catch(p){console.log("Exception at setupResults :"+p)}}
prevSelectedSkinConern=0;concernList=[];
function setupResults(a){prevSelectedSkinConern=0;concernList=a;try{if(null==a&&0!=a.length)console.log("featureList mull "),$(".results_left_panel_container").hide();else{$(".results_left_panel_container").show();var b=a.length,c=90,c=isMobile()?100:90,f=getElement("concerns_list");f.innerHTML="";getElement("app_container");for(var e=0;e<b;e++){var g=a[e],m=g.Severity,d=document.createElement("div");d.index=e;d.style.width=c+"px";var k=document.createElement("div");k.setAttribute("class","concern_severity");
var l=parseInt(.7*c);k.style.height=l+"px";var h=document.createElement("canvas");h.width=l;h.height=.9*l;drawCircle(h,4);drawSeverity(h,m,4,16);k.appendChild(h);var n=document.createElement("div");n.setAttribute("class","txt_concern");n.innerHTML=g.Name;d.appendChild(k);d.appendChild(n);f.appendChild(d)}}}catch(p){console.log("Exception at setupResults :"+p)}}
function onSkinConcernClicked(a){var b=getElement("concerns_list").children[prevSelectedSkinConern];try{onDeselectedConcern(b)}catch(c){}onSelectedConcern(a);prevSelectedSkinConern=a.index;getElement("result_img").src=dataEncodingHeader+concernList[prevSelectedSkinConern].Image;initImage("result_img")}function onSelectedConcern(a){a.className="skin_concern skin_concern_selected"}function onDeselectedConcern(a){a.className="skin_concern skin_concern_deselected"}
function drawSeverity(a,b,c,f){canWidth=a.width;a=a.getContext("2d");font="bold "+f+"pt Arial";textPointX=(canWidth-f/1.5)/2;textPointY=(canWidth+f/1)/2;a.beginPath();temp=1.50001+.4*b;a.arc(canWidth/2,canWidth/2,canWidth/3,1.5*Math.PI,temp*Math.PI,0);a.lineWidth=c;a.font=font;a.fillStyle="white";a.fillText(b,textPointX,textPointY);a.strokeStyle="#B63031";a.stroke()}
function drawCircle(a,b){canWidth=a.width;var c=a.getContext("2d");c.beginPath();temp=3.50001;c.arc(canWidth/2,canWidth/2,canWidth/3,1.5*Math.PI,temp*Math.PI,0);c.lineWidth=b;c.strokeStyle="#747a86";c.stroke()}
function clearClimateDetails(){document.getElementById("pollution_index").innerHTML="";document.getElementById("txt_pollution_value").innerHTML="";document.getElementById("txt_location_value").innerHTML="";document.getElementById("uv_index").innerHTML="";document.getElementById("txt_uv_value").innerHTML="";document.getElementById("skin_type_index").innerHTML="";document.getElementById("age_index").innerHTML="";document.getElementById("txt_gender").innerHTML="";$("#skin_type_selected_img").hide();
$("#Male_Female_img").attr("src","BTBP/img/Gender_Disabled_Icon.png")}function getDeepTagInfo(a){a=getServiceURL()+"GetDeepTagInfo/"+a+"/true?timestamp="+(new Date).getTime();HttpClient.Get(a,function(a){setUpDeepTagResults(a)},function(){console.log("CallDeepTagService service call failed")})}
function setUpDeepTagResults(a){var b=[],b=JSON.parse(a);for(a=0;a<b.Tags.length;a++)"GENDER"==b.Tags[a].TagName?($("#Male_Female_img").attr("src","BTBP/img/"+b.Tags[a].TagValue+".png"),$("#txt_gender").html="",document.getElementById("txt_gender").innerHTML=b.Tags[a].TagValue.toUpperCase()):"AGE"==b.Tags[a].TagName&&(document.getElementById("age_index").innerHTML=b.Tags[a].TagValue)}var isResultsBottomPanel=!0;
function toggleResultsBottonPanel(){var a=0;isResultsBottomPanel?(isResultsBottomPanel=!1,a=0,$("#toggle_bottom_results_panel_img").css({transform:"rotate("+a+"deg)"}),$("#tag_item_list_parent").slideUp()):(isResultsBottomPanel=!0,a=180,$("#toggle_bottom_results_panel_img").css({transform:"rotate("+a+"deg)"}),$("#tag_item_list_parent").slideDown())}function getLocation(){navigator.geolocation&&navigator.geolocation.getCurrentPosition(onSuccessLocation,onErrorLocation)}
function onErrorLocation(a){try{switch(a.code){case a.PERMISSION_DENIED:console.log("User denied the request for Geolocation.");break;case a.POSITION_UNAVAILABLE:console.log("Location information is unavailable.");break;case a.TIMEOUT:console.log("The request to get user location timed out.");break;case a.UNKNOWN_ERROR:console.log("An unknown error occurred.")}}catch(b){console.log("Exception at onErrorLocation :"+b)}}
function onSuccessLocation(a){Longitude=a.coords.longitude;Latitude=a.coords.latitude};
