var cameraErrorCode={CAMERA_NOT_FOUND:101,GET_USER_MEDIA_NOT_SUPPORTED:102,SECURE_CONNECTION_ERROR:103,PERMISSION_DINED:104,CAMERA_BUSY:105,UNKNOWN_ERROR:106};
(function(){function q(){var b=new dat.GUI({width:320});b.add(c.settings,"FLDPoints").name("Landmarks");b.add(c.settings,"FLDTriangles").name("Mask");-1!=btbpExample.appConfig.BeautyFeatureList.indexOf("Lipstick")&&(b.add(c.settings,"LipIntensity",0,1).name("Lipstick intensity"),b.add(c.settings,"LipGlossValue",0,1).name("Gloss intensity"));-1!=btbpExample.appConfig.BeautyFeatureList.indexOf("Foundation")&&b.add(c.settings,"FoundationIntensity",0,1).name("Foundation coverage");-1!=btbpExample.appConfig.BeautyFeatureList.indexOf("Complexion")&&
(b.add(c.settings,"Complexion"),b.add(c.settings,"ComplexionIntensity",0,1).name("Complexion evenness"));b.closed=!1;var a=document.getElementById("data-gui-container");a.innerHTML="";b.domElement.style.paddingBottom="30px";a.appendChild(b.domElement);b=document.createElement("div");b.setAttribute("class","settings_close");b.innerHTML="Close";b.onclick=onSettingsClicked;a.appendChild(b)}function r(){l=0;var b=document.getElementById("_lipshades");b.innerHTML="";var a,f;for(f in k){var d=k[f];a=document.createElement("li");
0==f?(a.setAttribute("class","shade_selected no_color_shade"),d=document.createElement("img"),d.setAttribute("class","no_shade_img"),d.src="BTBP/img/None_icon.png",a.appendChild(d)):a.setAttribute("class","shade_deselected");d=k[f].color;a.style.background="rgb("+d[0]+","+d[1]+","+d[2]+")";a.tag=f;a.onclick=function(){b.children[l].setAttribute("class","shade_deselected");var a=this.tag;c.settings.LipColor=k[a].color;this.setAttribute("class","shade_selected");l=a;c.settings.Lipstick=0==a?!1:!0};
b.appendChild(a)}}function m(){n=0;var b=s.getElement("_foundationshades");b.innerHTML="";var a,f;for(f in h){var d=h[f];a=document.createElement("li");if(0==f){a.setAttribute("class","shade_selected no_color_shade");var e=document.createElement("img");e.setAttribute("class","no_shade_img");e.src="BTBP/img/None_icon.png";a.appendChild(e)}else a.setAttribute("class","shade_deselected");a.style.background="rgb("+d[0]+","+d[1]+","+d[2]+")";a.tag=f;a.onclick=function(){b.children[n].setAttribute("class",
"shade_deselected");var a=this.tag;c.settings.FoundationShade=h[a];this.setAttribute("class","shade_selected");n=a;c.settings.Foundation=0==a?!1:!0};b.appendChild(a)}}function t(){var b=$("#tag_item_list_parent");if(g.deepTagMenu.isEnabled){b.show();LicensedDeepTags=[];for(var a=0;a<g.deepTagMenu.list.length;a++){var c=g.deepTagMenu.list[a];-1!=btbpExample.appConfig.DeepTagList.indexOf(c.featureName)?(LicensedDeepTags.push(c.tagName),$("#"+c.uiId).show()):$("#"+c.uiId).hide()}0==LicensedDeepTags.length&&
b.hide()}else b.hide();b=$("#concerns_list");if(g.skinFeatureMenu.isEnabled){b.show();a=[];LicensedFeatureTags=[];for(c=0;c<g.skinFeatureMenu.list.length;c++){var d=g.skinFeatureMenu.list[c];if(-1!=btbpExample.appConfig.SkinFeatureList.indexOf(d.featureName)){LicensedFeatureTags.push(d.tagName);var e=new skinConcern;e.Name=getFeatureNameByTagName(d.tagName);e.Severity="0";a.push(e)}}0<LicensedFeatureTags.length?setupFeatureResults(a):b.hide()}else b.hide();b=$("#controls_menu");a=g.beautyFeaturesMenu.list.length;
c=0;if(0<a){for(d=0;d<a;d++)if(e=g.beautyFeaturesMenu.list[d],-1!=btbpExample.appConfig.BeautyFeatureList.indexOf(e.featureName))switch(e.featureName){case "Lipstick":$("#lbl_lipShades").show();$("#lipsShades_container").show();$("#lbl_lipShades").parent().css({height:"100%"});c++;break;case "Foundation":$("#lbl_foundationShades").show(),$("#foundationshades_container").show(),0<c?($("#lbl_lipShades").parent().css({height:"50%"}),$("#lbl_foundationShades").parent().css({height:"50%"}),onLipstickShades()):
($("#lbl_lipShades").parent().css({height:"0%"}),$("#lbl_foundationShades").parent().css({height:"100%"}),onFoundationShades()),c++}else switch(e.featureName){case "Lipstick":$("#lbl_lipShades").hide();$("#lipsShades_container").hide();break;case "Foundation":$("#lbl_foundationShades").hide(),$("#foundationshades_container").hide()}0==c?b.hide():b.show()}else b.hide();0<LicensedDeepTags.length+LicensedFeatureTags.length?$("#deeptag_rejection_txt").show():$("#deeptag_rejection_txt").hide();0<btbpExample.appConfig.BeautyFeatureList.length+
LicensedDeepTags.length+LicensedFeatureTags.length?$("#restart_btn").show():$("#restart_btn").hide();btbpExample.config.isAutoRest=btbpExample.appConfig.auto_reset;btbpExample.config.resetTimeout=btbpExample.appConfig.auto_reset_time_interval;btbpExample.appConfig.show_settings?$("#settings_btn").show():$("#settings_btn").hide()}var c=btbpExample,s=c.dom,k=[{color:[255,255,255]},{color:[142,0,0]},{color:[142,0,71]},{color:[142,0,142]},{color:[236,118,118]}],h=[[255,255,255],[238,215,200],[230,202,
181],[223,189,164],[216,174,149],[213,168,132],[206,152,122],[198,140,113],[184,133,105],[178,117,95],[165,110,86],[145,108,83],[132,95,67],[120,85,57],[107,80,68],[94,68,45],[84,47,31]],p=!0;c.callbacks={onCameraError:function(b){var a="";switch(b){case cameraErrorCode.CAMERA_NOT_FOUND:a="Camera is not available!";break;case cameraErrorCode.GET_USER_MEDIA_NOT_SUPPORTED:a="Camera Api not supported!";break;case cameraErrorCode.SECURE_CONNECTION_ERROR:a="Only secure origins are allowed!";break;case cameraErrorCode.PERMISSION_DINED:a=
"Camera permission denied!";break;case cameraErrorCode.CAMERA_BUSY:a="Camera is busy!";break;case cameraErrorCode.UNKNOWN_ERROR:a="Unknown error!";break;case fileErrorCodes.NO_FILE_SELECTED:a="No File selected!";break;case fileErrorCodes.FILE_FORMAT_NOT_SUPPORTED:a="Invalid file format!<br/> Please select Image of type BMP, JPG or PNG";break;case fileErrorCodes.FILE_SIZE_TOO_LOW:a="File size is too small!<br/> Please continue by uploading photo";break;case fileErrorCodes.FILE_SIZE_TOO_HIGHT:a="File size is too large!<br/> Please uploading another image";
break;case fileErrorCodes.FILE_READING_FAILED:a="File Api not supported!";break;case fileErrorCodes.INTERVAL_ERROR:a="Some thing went wrong!<br/> Please try again";break;case fileErrorCodes.FILE_API_NOT_SUPPORTED:a="File Api not supported!<br/> Please try again"}b=a;if(void 0==b||0==b.length)b="Camera is not available or busy";$("#loader_launch_screen").hide();$("#error_message").html(b);$("#error_container").show();clearInterval(loaderInterval)},showDataGUI:function(){gui.closed=!1},toggleDataGUI:function(){p?
($("#data-gui-container").animate({right:"0px"},"slow"),p=!1):($("#data-gui-container").animate({right:"-320px"},"slow"),p=!0)},resetApp:function(){onRestartClicked()}};c.settings=new function(){this.Lipstick=this.FLDTriangles=this.FLDPoints=!1;this.LipIntensity=.33;this.LipGlossValue=.5;this.Foundation=!1;this.FoundationIntensity=.3;this.Complexion=!0;this.ComplexionIntensity=.5;this.LipColor=[142,0,0];this.FoundationShade=[238,215,200];this.MatchFoundation=!0;this.foudataionShades=h;this.isAnalysisStated=
!1;this.resetFoundation=function(){btbpExample.settings.MatchFoundation=!0;btbpExample.settings.Foundation=!0};this.reset=function(){c.settings.FLDPoints=!1;c.settings.FLDTriangles=!1;c.settings.Lipstick=!1;c.settings.LipIntensity=.33;c.settings.LipGlossValue=.5;c.settings.Foundation=!1;c.settings.FoundationIntensity=.3;c.settings.Complexion=!0;c.settings.ComplexionIntensity=.5;c.settings.LipColor=[142,0,0];c.settings.FoundationShade=[238,215,200];c.settings.MatchFoundation=!0;c.settings.foudataionShades=
h;c.settings.isAnalysisStated=!1;q();r();m();t()};this.saveImage=function(){var b=document.getElementById("_saveImage"),a=document.getElementById("_imageData").toDataURL("image/png");b.setAttribute("href",a);b.click()};this.setFoundationShade=function(b){m();var a=s.getElement("_foundationshades").children[b];a.click();var c=document.createElement("div");c.setAttribute("class","mathced_shade");c.innerHTML="Your Match";a.appendChild(c);a.style.boxShadow="1px 1px 10px 3px #B63031";$("#_foundationshades").animate({scrollLeft:30*
b},500)}};q();r();var l=0;m();var n=0,g={deepTagMenu:{isEnabled:!0,list:[{featureName:"Gender",uiId:"gender_item",tagName:DeepTags.GENDER,isEnabled:!1},{featureName:"Age",uiId:"age_item",tagName:DeepTags.AGEGROUP,isEnabled:!1},{featureName:"Skin Type",uiId:"skin_type_item",tagName:DeepTags.SKINTYPE,isEnabled:!1},{featureName:"Air Quality",uiId:"pollution_item",tagName:DeepTags.POLLUTION_AQI,isEnabled:!1},{featureName:"Location",uiId:"location_item",tagName:DeepTags.GEOLOCATION_CITY,isEnabled:!1},
{featureName:"UV Index",uiId:"uv_item",tagName:DeepTags.UVINDEX,isEnabled:!1}]},skinFeatureMenu:{isEnabled:!0,list:[{featureName:"Wrinkles",tagName:DeepTags.WRINKLES_SEVERITY_SCORE,isEnabled:!1},{featureName:"Acne",tagName:DeepTags.ACNE_SEVERITY_SCORE,isEnabled:!1},{featureName:"Pores",tagName:DeepTags.PORES_SEVERITY_SCORE,isEnabled:!1},{featureName:"Spots",tagName:DeepTags.SPOTS_SEVERITY_SCORE,isEnabled:!1},{featureName:"Redness",tagName:DeepTags.REDNESS_SEVERITY_SCORE,isEnabled:!1},{featureName:"Uneven SkinTone",
tagName:DeepTags.UNEVEN_SKINTONE_SEVERITY_SCORE,isEnabled:!1},{featureName:"Dark Circles",tagName:DeepTags.DARK_CIRCLES_SEVERITY_SCORE,isEnabled:!1},{featureName:"Lips",tagName:DeepTags.LIP_ROUGHNESS_SEVERITY_SCORE,isEnabled:!1},{featureName:"Dehydration",tagName:DeepTags.DEHYDRATION_SEVERITY_SCORE,isEnabled:!1},{featureName:"Oiliness",tagName:DeepTags.OILINESS_SEVERITY_SCORE,isEnabled:!1}]},beautyFeaturesMenu:{list:[{featureName:"Lipstick",isEnabled:!1},{featureName:"Foundation",isEnabled:!1},{featureName:"Complexion",
isEnabled:!1}]}};t()})();
