(function(){var a=btbpExample.drawing,z=btbpExample.settings,g=function(a,e){return"undefined"!==typeof a?a:e};a.setup=function(f,e,c){a.stage=new createjs.Stage(f);a.faceTextures=e;a.container=new createjs.Container;a.clickArea=new createjs.Shape;a.drawSprite=new createjs.Shape;a.imageContainer=new createjs.Container;a.draw=a.drawSprite.graphics;a.onUpdateCallback=null;a.container.addChild(a.drawSprite);a.container.addChild(a.imageContainer);a.container.addChild(a.clickArea);a.stage.addChild(a.container);
"undefined"===typeof c&&(c=30);createjs.Ticker.setFPS(c);createjs.Ticker.addEventListener("tick",a.stage)};a.updateLayout=function(f,e){a.clickArea.graphics.clear();a.clickArea.graphics.beginFill("#ffffff");a.clickArea.graphics.drawRect(0,0,f,e);a.clickArea.graphics.endFill();a.clickArea.alpha=.01;a.clickArea.cursor="pointer";a.stage.canvas.width=f;a.stage.canvas.height=e;a.faceTextures.width=f;a.faceTextures.height=e;a.stage.update()};a.setUpdateCallback=function(f){null!=a.onUpdateCallback&&(a.stage.removeEventListener("tick",
a.onUpdateCallback),a.onUpdateCallback=null);null!=f&&(a.onUpdateCallback=f,a.stage.addEventListener("tick",a.onUpdateCallback))};a.clear=function(){a.draw.clear();a.faceTextures&&a.faceTextures.getContext("2d").clearRect(0,0,a.faceTextures.width,a.faceTextures.height)};a.getColor=function(a,e){return createjs.Graphics.getRGB(a>>16&255,a>>8&255,a&255,e)};var n=a.getColor;a.drawVertices=function(f,e,c,d,b){c=g(c,!1);e=g(e,2);d=g(d,41215);b=g(b,1);d=n(d,b);b=a.draw;c&&b.clear();c=0;for(var m=f.length;c<
m;){var p=f[c++],h=f[c++];b.beginFill(d);b.drawCircle(p,h,e);b.endFill()}};a.drawTriangles=function(f,e,c,d,b,m){c=g(c,!1);d=g(d,.5);b=g(b,41215);m=g(m,.85);b=n(b,m);m=a.draw;c&&m.clear();c=0;for(var p=e.length;c<p;){var h=e[c],k=e[c+1],l=e[c+2],q=f[2*h],h=f[2*h+1],r=f[2*k],k=f[2*k+1],v=f[2*l],l=f[2*l+1];m.setStrokeStyle(d);m.beginStroke(b);m.moveTo(q,h);m.lineTo(r,k);m.lineTo(v,l);m.lineTo(q,h);m.endStroke();c+=3}};a.drawFoundation=function(f,e,c,d,b){d=g(d,!1);var m=a.draw;d&&m.clear();btbpExample.features.applyFoundation(f,
a.faceTextures,e,c,b)};a.drawComplexion=function(f,e,c,d){d=g(d,!1);var b=a.draw;d&&b.clear();btbpExample.features.applyComplexion(f,a.faceTextures,e,c)};a.drawLipStick=function(f,e,c,d){d=g(d,!1);var b=a.draw;d&&b.clear();z.Foundation||z.Complexion?btbpExample.features.applyLipstick(a.faceTextures,a.faceTextures,e,c):btbpExample.features.applyLipstick(f,a.faceTextures,e,c)};a.fillTriangles=function(f,e,c,d,b){c=g(c,!1);d=g(d,41215);b=g(b,.85);d=n(d,b);b=a.draw;c&&b.clear();c=0;for(var m=e.length;c<
m;){var p=e[c],h=e[c+1],k=e[c+2],l=f[2*p],p=f[2*p+1],q=f[2*h],h=f[2*h+1],r=f[2*k],k=f[2*k+1];b.beginFill(d);b.moveTo(l,p);b.lineTo(q,h);b.lineTo(r,k);b.lineTo(l,p);b.endFill();c+=3}};a.drawTexture=function(f,e,c,d){if(a.faceTextures)for(var b=a.faceTextures.getContext("2d"),g=0,p=e.length;g<p;g+=3){var h=e[g],k=e[g+1],l=e[g+2],q=f[2*h],r=f[2*h+1],v=f[2*k],n=f[2*k+1],w=f[2*l],x=f[2*l+1],s=c[2*h]*d.width,h=c[2*h+1]*d.height,t=c[2*k]*d.width,k=c[2*k+1]*d.height,u=c[2*l]*d.width,l=c[2*l+1]*d.height;b.save();
b.beginPath();b.moveTo(q,r);b.lineTo(v,n);b.lineTo(w,x);b.closePath();b.clip();var y=s*k+h*u+t*l-k*u-h*t-s*l;b.setTransform((q*k+h*w+v*l-k*w-h*v-q*l)/y,(r*k+h*x+n*l-k*x-h*n-r*l)/y,(s*v+q*u+t*w-v*u-q*t-s*w)/y,(s*n+r*u+t*x-n*u-r*t-s*x)/y,(s*k*w+h*v*u+q*t*l-q*k*u-h*t*w-s*v*l)/y,(s*k*x+h*n*u+r*t*l-r*k*u-h*t*x-s*n*l)/y);b.drawImage(d,0,0);b.restore()}};a.drawRect=function(f,e,c,d,b){e=g(e,!1);c=g(c,1);d=g(d,41215);b=g(b,1);d=n(d,b);b=a.draw;e&&b.clear();b.setStrokeStyle(c);b.beginStroke(d);b.drawRect(f.x,
f.y,f.width,f.height);b.endStroke()};a.drawRects=function(f,e,c,d,b){e=g(e,!1);c=g(c,1);d=g(d,41215);b=g(b,1);d=n(d,b);b=a.draw;e&&b.clear();b.setStrokeStyle(c);b.beginStroke(d);e=0;for(c=f.length;e<c;e++)d=f[e],b.drawRect(d.x,d.y,d.width,d.height);b.endStroke()};a.drawPoint=function(f,e,c,d,b){c=g(c,!1);e=g(e,2);d=g(d,41215);b=g(b,1);d=n(d,b);b=a.draw;c&&b.clear();b.beginFill(d);b.drawCircle(f.x,f.y,e);b.endFill()};a.drawPoints=function(f,e,c,d,b){c=g(c,!1);e=g(e,2);d=g(d,41215);b=g(b,1);d=n(d,b);
b=a.draw;c&&b.clear();c=0;for(var m=f.length,p;c<m;c++)p=f[c],b.beginFill(d),b.drawCircle(p.x,p.y,e),b.endFill()}})();
